@echo off
title Starting Projects...

echo Starting Spring Boot backend...
start "Backend" cmd /k "cd /d backend\back && mvnw spring-boot:run"

echo Starting Angular frontend...
start "Frontend" cmd /k "cd /d frontend && ng serve"

echo Both projects are starting...
exit